// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3rXFfacvZwbL_qbXNV3ufLCCAFv0FXvc',
    appId: '1:1057650422854:web:cad1db6ca136858a980647',
    messagingSenderId: '1057650422854',
    projectId: 'flutter-3d165',
    authDomain: 'flutter-3d165.firebaseapp.com',
    storageBucket: 'flutter-3d165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrjdwpLfr0NjCcAZ9DEdfTsoz7G9inE4',
    appId: '1:1057650422854:android:44a56e130c541568980647',
    messagingSenderId: '1057650422854',
    projectId: 'flutter-3d165',
    storageBucket: 'flutter-3d165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZd1jqIa60yHRohpjqNg_APAxtwOOkZ1M',
    appId: '1:1057650422854:ios:74ca3392d7ce1fcb980647',
    messagingSenderId: '1057650422854',
    projectId: 'flutter-3d165',
    storageBucket: 'flutter-3d165.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZd1jqIa60yHRohpjqNg_APAxtwOOkZ1M',
    appId: '1:1057650422854:ios:74ca3392d7ce1fcb980647',
    messagingSenderId: '1057650422854',
    projectId: 'flutter-3d165',
    storageBucket: 'flutter-3d165.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3rXFfacvZwbL_qbXNV3ufLCCAFv0FXvc',
    appId: '1:1057650422854:web:9215274a48351309980647',
    messagingSenderId: '1057650422854',
    projectId: 'flutter-3d165',
    authDomain: 'flutter-3d165.firebaseapp.com',
    storageBucket: 'flutter-3d165.firebasestorage.app',
  );
}
